### PR TITLE
No crypto

### PR DESCRIPTION
**Pull request by guysv**
This PR really just comments out anything crypto-api-related so rendezvous exchange could be used before figuring out [js-libp2p-crypto/125](https://github.com/libp2p/js-libp2p-crypto/pull/125)

Because the crypto will be figured out eventually, I guess commenting out blocks is not the most wise way of managing code, so I would love some comments on that.

### CODE REVIEW

**Comment by mkg20001** [comment]
One way would be to squash all the changes into one commit like "[TMP] Remove crypto until $PRURL is sorted out"

Another way would be to hide crypto behind a flag, so that it can be tested during the development of the matching crypto-apis

**Comment by mkg20001** [comment]
Also, just a general note: Currently I'm busy with work _and_ school projects (yes, something like that is possible) with deadlines due next week. So, basically: Be patient on merges and anything more than mere comments.

**Comment by guysv** [comment]
Hey, just pinging the thread.

**Comment by mkg20001** [comment]
@guysv Since crypto already works on nodeJS it would be great if it could be hidden behind a flag for dev. Unsure how bad the conflicts will get if we'll start working on the code without crypto and then revert this commit.

**Comment by guysv** [comment]
@mkg20001 but that won't be compatible with peers who are capable of securing the coms, not without modifying the protocol at least, also i'm not sure if such thing (requesting peers to turn off encryption) opens a door to a downgrade attack.

**Comment by mkg20001** [comment]
> but that won't be compatible with peers who are capable of securing the coms

The nodeJS crypto already works. The point is to have separate secure & insecure modes that will be switched on release. The breakage with switching would be the same, but tests could still be run with it turned on so no code would "waste away".

**Comment by guysv** [comment]
alright, expect a commit soon :)

**Comment by guysv** [comment]
_Here it is_. Gotta admit the whole endeavor could go nicer if we used promises instead of callbacks. oh well.

Also, how do I get the nodejs tests to pass with encryption as you said? Do I need to update some dep?

Another thing, right now encryption is **enabled** by default, although still missing. Should I flip the flag?

**Review by mkg20001 — APPROVED** [review]
:tada: Thx, LGTM

**Comment by mkg20001** [comment]
> Here it is. Gotta admit the whole endeavor could go nicer if we used promises instead of callbacks. oh well.

Waiting for libp2p async/await, so we don't have any cb<->promise compatibility mess here

> Another thing, right now encryption is enabled by default, although still missing. Should I flip the flag?

I'll do that

> Also, how do I get the nodejs tests to pass with encryption as you said? Do I need to update some dep?

There's a branch with the encrypt/decrypt functions, https://github.com/libp2p/js-libp2p-crypto/pull/125

You'd need to clone & link peer-id, then clone & link libp2p-crypto into peer-id.
So basically `libp2p-exchange-rendezvous#master -> peer-id#master -> libp2p-crypto#feat/rsa-enc-dec`

**Comment by mkg20001** [comment]
Also sorry for missing your comment, somehow turns out reviewing stuff while being in public transport doesn't go well :sweat_smile:

**Comment by mkg20001** [comment]
Seems like browser tests are still broken. Going to investigate when I get some more time

**Pull request merged**
